do the fialure control completely manually

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,24 +24,30 @@ runs:
   using: composite
   steps:
     - if: runner.os == 'Linux'
-      continue-on-error: true
       name: Install cargo-get
       run: |
-        current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
-        download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep x86_64-unknown-linux-musl\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
-        mkdir -p ~/.cargo/bin/
-        curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
-        chmod +x ~/.cargo/bin/cargo-get
+        download_cargo_get() {
+          current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
+          download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep x86_64-unknown-linux-musl\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
+          mkdir -p ~/.cargo/bin/
+          curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
+          chmod +x ~/.cargo/bin/cargo-get
+        }
+
+        download_cargo_get || echo "Failed for some reason!"
       shell: bash
     - if: runner.os == 'macOS'
-      continue-on-error: true
       name: Install cargo-get
       run: |
-        current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
-        download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep x86_64-apple-darwin\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
-        mkdir -p ~/.cargo/bin/
-        curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
-        chmod +x ~/.cargo/bin/cargo-get
+        download_cargo_get() {
+          current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
+          download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep x86_64-apple-darwin\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
+          mkdir -p ~/.cargo/bin/
+          curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
+          chmod +x ~/.cargo/bin/cargo-get
+        }
+
+        download_cargo_get || echo "Failed for some reason!"
       shell: bash
     - name: Resort to building the binary if we can't find a prebuilt one
       run: |
